// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk2tgJue9Q1ZwXPfe5GCiWgTwN_G6XIpE',
    appId: '1:137900097757:web:b46e98690518431c411b34',
    messagingSenderId: '137900097757',
    projectId: 'asian-paradise-de6ab',
    authDomain: 'asian-paradise-de6ab.firebaseapp.com',
    storageBucket: 'asian-paradise-de6ab.firebasestorage.app',
    measurementId: 'G-EHGC249V8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP5Okng6m2F4BwKGMMR_qA5m1-KdMtvI8',
    appId: '1:137900097757:android:49ec674dff92d976411b34',
    messagingSenderId: '137900097757',
    projectId: 'asian-paradise-de6ab',
    storageBucket: 'asian-paradise-de6ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQUkxnlcWrDaoHS4oVbKvbRxJMJ8Yb3B8',
    appId: '1:137900097757:ios:3719422d9cd8f439411b34',
    messagingSenderId: '137900097757',
    projectId: 'asian-paradise-de6ab',
    storageBucket: 'asian-paradise-de6ab.firebasestorage.app',
    iosBundleId: 'com.example.asianParadise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQUkxnlcWrDaoHS4oVbKvbRxJMJ8Yb3B8',
    appId: '1:137900097757:ios:3719422d9cd8f439411b34',
    messagingSenderId: '137900097757',
    projectId: 'asian-paradise-de6ab',
    storageBucket: 'asian-paradise-de6ab.firebasestorage.app',
    iosBundleId: 'com.example.asianParadise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk2tgJue9Q1ZwXPfe5GCiWgTwN_G6XIpE',
    appId: '1:137900097757:web:f8bddc74f3e39de0411b34',
    messagingSenderId: '137900097757',
    projectId: 'asian-paradise-de6ab',
    authDomain: 'asian-paradise-de6ab.firebaseapp.com',
    storageBucket: 'asian-paradise-de6ab.firebasestorage.app',
    measurementId: 'G-LDNXF4QXKP',
  );
}
